sudo: required

language: scala

scala:
   - 2.11.11

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2.3

before_install:
  - docker-compose build

script:
  - docker-compose -f "docker-compose.yml" run --rm --service-ports --entrypoint "/bin/bash -c" "api-server" "sbt"
  - compile
