version: '2.3'
services:
  postgres:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    volumes:
      - ./data/:/tmp/data/
    env_file: .env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-server:
    image: a-breakable-toy
    build:
      context: ./app-backend
    links:
      - postgres:database.service.aaronxsu.toy
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "4567:4567"
    volumes:
      - ./app-backend/:/opt/a-breakable-toy/app-backend/
      - ./.sbt:/root/.sbt
      - ./.bintray:/root/.bintray
      - $HOME/.aws:/root/.aws:ro
    entrypoint: sbt
    command:
      - "run"
      - "-Dcom.sun.management.jmxremote.rmi.port=4567"
      - "-Dcom.sun.management.jmxremote=true"
      - "-Dcom.sun.management.jmxremote.port=4567"
      - "-Dcom.sun.management.jmxremote.ssl=false"
      - "-Dcom.sun.management.jmxremote.authenticate=false"
      - "-Dcom.sun.management.jmxremote.local.only=false"
      - "-Djava.rmi.server.hostname=localhost"
