#!/bin/bash

set -eu

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Builds/Pulls containers for project

Example: ./scripts/bootstrap
"
}

function main() {
    echo "Building/Pulling containers..."
    # build all containers in the docker-compose file
    docker-compose \
        -f "${DIR}/../docker-compose.yml" \
        build
    # # pull the postgres image without starting the service.
    # docker-compose \
    #     -f "${DIR}/../docker-compose.yml" \
    #     pull postgres
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then

    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        main
    fi
    exit
fi
